### ISSUE TITLE
Rollback functionality

### ISSUE THREAD

**Issue by alekseyp** [f500/ansible-project_deploy#16]
Hi there,

Has anyone found an easy way to do a rollback? My problem is that timestamps are different from server to server , so it's impossible to just change the -current- symlink.

Capistrano for example is creating the same timestamp on all servers.

Current example:
```
lrwxrwxrwx  1 root root   53 Feb  5 02:44 current -> /.../releases/20150205024358
lrwxrwxrwx  1 root root   53 Feb  5 02:44 current -> /.../releases/20150205024359
lrwxrwxrwx  1 root root   53 Feb  5 02:44 current -> /.../releases/20150205024358
```

Is anyone interested in that functionality?

**Comment by ramondelafuente** [comment]
I wrote some about the thought that went into this role, and rollbacks with Ansible are a bit of an issue.
http://future500.nl/articles/2014/07/thoughts-on-deploying-with-ansible/

Than being said, I think you note two points of interest:

- you might prefer the same timestamp on all servers.
- you don't want a rollback _during_ a deploy, but a separate playbook

#### Having the same timestamp on all servers

This role (or rather the underlying [module](https://galaxy.ansible.com/list#/roles/2266) ) won't force a timestamp on you. So you can do `deploy_helper: path=/path/to/root release=[some release string] state=present` and the `deploy.new_release` would reflect whatever you decided to put in.

    ansible-playbook deploy.yml -i hosts --extra-vars "timestamp=`date +%Y%m%d%H%i%s`"

Translated to the role, we should add a `project_release` variable that defaults to the deploy.new_release  if it's empty. I'll think on this some more, because it has some implications (we only generate the new_release variable once the module has run, so we cannot properly default it, the module might also require a change). Ansible 1.8 can remove parameters if the value is empty, but I'm not sure I want to enforce version 1.8 as a minimum for this role just yet.

#### Having a separate playbook for rollbacks

There are two facts in the deploy_helper module that can be of use here: `previous_release` and `previous_release_path`. These point to whatever the release the current symlink points to.  You could use that - but I do realise now that there is also no way to get the release _before_. Perhaps the module could use an additional fact with a list of releases... as well as a `state=rollback` that can point the symlink to the one before the current one.

It would be a bit odd that this state should never be called in a deploy procedure, but I do see how it would make life much easier.


Good questions!

**Comment by alekseyp** [comment]
@ramondelafuente, thanks for your fast and very detailed reply.
Using `deploy_helper` and separate roll sounds like an easy fix.

I have one question tho, maybe a bit silly :) What is the correct way of using `deploy_helper`?
Do I need to create my own playbook with all the commands to deploy? Or can I just somehow simple assign new value to `deploy_helper: release` somehow via variables?

**Comment by alekseyp** [comment]
Right now i have a playbook that looks like that:

```
- hosts: app-servers
  user: {{ deploy_user }}
  roles:
    - f500.project_deploy
```

and then my `group_vars/all` file with all the configurations.

**Comment by ramondelafuente** [comment]
The role does not support it yet, I am afraid... because the task simply does `deploy_helper: ... state=present` without passing a timestamp. So the role needs to be changed, but I believe ansible only started supporting "optional parameters" in 1.8. (and I don't want to rely on it because of distro's like this: http://packages.ubuntu.com/search?keywords=ansible)

http://docs.ansible.com/playbooks_variables.html#omitting-undefined-variables-and-parameters

We could also change the module, so that passing a Null value defaults to using the generated timestamp. This would not require Ansible 1.8, so I think that's the way we could go.  _but_ the module is in the process of being added to ansible-extra-modules, so I don't want to mess with it too much while the jury is still out...

**Comment by ramondelafuente** [comment]
You playbook looks perfect to me, exactly like we envisioned. Super clean and re-usable between projects.

**Comment by ramondelafuente** [comment]
Yet another request to support all the deploy_helper module parameters, see #17

**Comment by ramondelafuente** [comment]
The Ansible modules-extra repo is once again in motion. I'm going to do a last run and try to add the parameters to the module _before_ the merge.

**Comment by dpkp** [comment]
perhaps use 2 finalize tasks, one for current and a second w/ `current_path: rollback`. To rollback, set current_deploy_helper.release = rollback_deploy_helper.previous_release, then finalize both as usual. This does not require keeping version timestamps in sync across nodes.

**Comment by ramondelafuente** [comment]
Hey all. Thanks for hanging in there for so long :-)

The problem being solved here is having the same release name for all nodes. This is now possible (please update to version ^ v3.1.0) by setting a variable `project_release`. It requires Ansible version 1.8 and up as stated, but the role requirements were already updated long ago... (I really should spend more time combing old issues)

The dependency on the `F500.project_deploy_module` was also dropped, as Ansible 2.0 now ships with the deploy_helper module by default in Ansible Modules Extra! W00TW00T
